name: Deploy to Amazon ECS

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::688948287774:role/EC2CodeDeployRole
          aws-region: ca-central-1

      - name: Deploy to AWS via CodeDeploy
        uses: aws-actions/aws-codedeploy-github-actions@v1.0.1
        with:
          application-name: Teaching-Platform
          deployment-group: Teaching-Platform-Grp
          deployment-config-name: CodeDeployDefault.AllAtOnce
          #github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run post-deployment script
        run: |
          cd /home/ec2-user/Teaching-Platform/client
          npm run build
          mv -f build/ ../server/client/build
          pm2 restart all
          sudo systemctl restart nginx
        shell: bash
