name: Deploy to AWS EC2 using CodeDeploy

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Trigger CodeDeploy deployment
        run: |
          aws deploy create-deployment \
            --application-name Teaching-Platform \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name Teaching-Platform-Deployment-Group \
            --github-location repository=humbeatbox/Teaching-Platform,commitId=$(git rev-parse HEAD)
