name: Deploy to AWS EC2 using CodeDeploy

on:
  workflow_run:
    workflows: ["Lint and Test"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install and build client
        run: |
          cd client
          npm install
          npm run build

      - name: Transfer build folder to EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_HOST }} "rm -rf ${{ secrets.EC2_APP_PATH }}/build"
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r client/build ec2-user@${{ secrets.EC2_HOST }}:${{ secrets.EC2_APP_PATH }}/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Trigger CodeDeploy deployment
        run: |
          aws deploy create-deployment \
            --application-name Teaching-Platform \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name Teaching-Platform-Deployment-Group \
            --github-location repository=humbeatbox/Teaching-Platform,commitId=$(git rev-parse HEAD)
